name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # update version
      - name: Bump version and create new tag
        id: bump_version
        run: |
          git config --global user.email "${{ secrets.ADMIN_EMAIL }}"
          git config --global user.name "${{ secrets.ADMIN_NAME }}"
          git add package.json package-lock.json
          git commit -m "chore: update version"
          npm version patch -m "chore(release): bump version to %s"
          echo "new_version=$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV

      # version update in git and push
      - name: Push changes to release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b release-${{ github.run_number }}
          git push origin release-${{ github.run_number }}

      # circumvent the branch protect rules
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update version to ${{ steps.bump_version.outputs.new_version }}"
          branch: release-${{ github.run_number }}
          base: main
          title: "Release ${{ steps.bump_version.outputs.new_version }}"
          body: "Automated release created by GitHub Actions."
          
      # Enable Auto Merge for the Pull Request
      - name: Enable Auto-Merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create-pull-request.outputs.pull-request-number }}
          merge-method: squash
